In [1]:
import pandas as pd

In [4]:
df_16 = pd.read_csv("data/Dhaka_PM2.5_2016.csv")
df_17 = pd.read_csv("data/Dhaka_PM2.5_2017.csv")
df_18 = pd.read_csv("data/Dhaka_PM2.5_2018.csv")
df_19 = pd.read_csv("data/Dhaka_PM2.5_2019.csv")
df_20 = pd.read_csv("data/Dhaka_PM2.5_2020.csv")
df_21 = pd.read_csv("data/Dhaka_PM2.5_2021.csv")
df_22 = pd.read_csv("data/Dhaka_PM2.5_2022.csv")

In [13]:
df_22

,Date (LT),Hour,NowCast Conc.,Raw Conc.,Conc. Unit,AQI,AQI Category,QC Name
0,01/01/2022 02:00,2,130.1,129,ug/m3,190,Unhealthy,Valid
1,01/01/2022 03:00,3,128.1,126,ug/m3,188,Unhealthy,Valid
2,01/01/2022 04:00,4,125.1,121,ug/m3,187,Unhealthy,Valid
3,01/01/2022 05:00,5,125.6,126,ug/m3,187,Unhealthy,Valid
4,01/01/2022 06:00,6,124.2,120,ug/m3,186,Unhealthy,Valid
...,...,...,...,...,...,...,...,...
3526,31/05/2022 21:00,21,61.0,52,ug/m3,154,Unhealthy,Valid
3527,31/05/2022 22:00,22,62.0,63,ug/m3,154,Unhealthy,Valid
3528,31/05/2022 23:00,23,60.5,59,ug/m3,154,Unhealthy,Valid
3529,01/06/2022 00:00,0,108.7,157,ug/m3,178,Unhealthy,Valid
3530,01/06/2022 01:00,1,118.3,128,ug/m3,183,Unhealthy,Valid